server:
  port: 8081

dubbo:
  application:
    # 服务名称
    name: consumer
  registry:
    # 注册中心地址
    address: zookeeper://mecs.com:2181
#    address: zookeeper://10.37.253.31:2181
    timeout: 60000
  scan:
    basePackages: com.dubbo.provider.service