eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
  zipkin:
    rabbitmq:
      queue: zipkin
#    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

  rabbitmq:
    host: 192.168.71.254
    port: 5672
    username: admin
    password: admin