spring:
  application:
    name: dubbo-provider

dubbo:
  application:
  # 服务名称
  registry:
  # 注册中心地址
#    address: zookeeper://10.37.253.31:2181
    address: zookeeper://mecs.com:2181          # N/A
    timeout: 60000
  protocol:
    name: dubbo
    port: 20800
  scan:
    basePackages: com.dubbo.provider.service
  server: true


