spring:
  redis:
    host: 192.168.155.150
    port: 6379
    password: Yixin4redis

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 1.104.190.82:9300 #, 47.104.190.82:9300
      repositories:
        enabled: true
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 1
#      rest:
#        uri: http://localhost:7474
#      mybatis:
#        uri: jdbc:neo4j:bolt://ip:port
#mybatis:
#  neo4j:
#    config:
#      file: neo4j/mybatis-config-neo4j.xml



    type: com.alibaba.druid.pool.DruidDataSource
    #      driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://mecs.com:3306/tdatabase?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&allowMultiQueries=true&useCursorFetch=true
    username: root
    password: 1
    mybatis:
      mapper-locations: classpath:mapper/*.xml

server:
  port: 8887





management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["prometheus","health"]

endpoints:
  prometheus:
    id: metrics
